### PR TITLE
Fix bios_mem_map end address confusion, preserve a copy for kexec

### LINKED ISSUE #72: Incorrect passing of e820 memory map to Linux kexec guests
The following 2 excerpts are from the same live-bootstrap qemu session.

Fiwix reported the memory map as follows:
```
memory    0x0000000000000000-0x000000000009fbff available
          0x000000000009fc00-0x000000000009ffff reserved
          0x00000000000f0000-0x00000000000fffff reserved
          0x0000000000100000-0x00000000bffdffff available
          0x00000000bffe0000-0x00000000bfffffff reserved
          0x00000000feffc000-0x00000000feffffff reserved
          0x00000000fffc0000-0x00000000ffffffff reserved
          0x0000000100000000-0x000000013fffffff available
```

Then, after kexec, Linux reports:
```
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009cfff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009d000-0x000000000009efff] reserved
[    0.000000] BIOS-e820: [mem 0x000000000009f000-0x000000000009fbfe] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009fffe] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000ffffe] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000bffdfffe] usable
[    0.000000] BIOS-e820: [mem 0x00000000bffe0000-0x00000000bffffffe] reserved
[    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000fefffffe] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000fffffffe] reserved
[    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000013ffffffe] usable
```

Two oddities are visible:

1. All of the memory regions reported by Fiwix are missing one byte at the end, when re-reported by Linux.
2. An additional reservation is visible in the range 9d000-9efff. This block, for some reason, doesn't have the off-by-1 ending seen in other blocks.

### PR DESCRIPTION
**Pull request by Googulator**
- Consistently treat the end / "to" address as an inclusive value, i.e. the highest address that belongs to the range.
- Preserve a copy of the memory map as returned by the BIOS or the bootloader, before any in-kernel reservations, for kexec guests.

Fixes #72

### CODE REVIEW

**Comment by Googulator** [comment]
Currently testing this fix in live-bootstrap.

File: include/fiwix/bios.h [hunk 1]
```diff
@@ -20,6 +20,7 @@ struct bios_mem_map {
 	int type;
 };
 extern struct bios_mem_map bios_mem_map[NR_BIOS_MM_ENT];
+extern struct bios_mem_map orig_bios_mem_map[NR_BIOS_MM_ENT];
```
Comment (mikaku) [inline include/fiwix/bios.h:23]: If there will not be a completely different `bios_mem_map()` function, what's the point to rename it to `orig_bios_mem_map()`?

I mean, if there is only one function doing the work, why this change in its name?

Its original name already indicates that this is the original BIOS memory map.

**Comment by Googulator** [comment]
Confirming that this fixes the issue.
